language: node_js
node_js:
  - "10"
script:
  - npm run build:ghpages
deploy:
  provider: pages
  local_dir: "dist"
  github_token: $GITHUB_TOKEN
  skip_cleanup: true
  keep_history: true
  on:
    branch: master